import { WorkoutType, Exercise } from "./types";

export const workoutTypes: WorkoutType[] = [
  {
    id: "wt-strength",
    name: "Strength Training",
    category: "Strength",
    description: "Build muscle and increase strength with resistance exercises",
    icon: "Dumbbell",
  },
  {
    id: "wt-cardio",
    name: "Cardio",
    category: "Cardio",
    description: "Improve cardiovascular fitness and endurance",
    icon: "Heart",
  },
  {
    id: "wt-hiit",
    name: "HIIT",
    category: "HIIT",
    description: "High intensity interval training for maximum calorie burn",
    icon: "Zap",
  },
  {
    id: "wt-flexibility",
    name: "Flexibility & Mobility",
    category: "Flexibility",
    description: "Improve range of motion and reduce injury risk",
    icon: "Stretching",
  },
  {
    id: "wt-sport",
    name: "Sport Specific",
    category: "Sport",
    description: "Training tailored to specific sports and activities",
    icon: "Trophy",
  },
];

export const exercises: Exercise[] = [
  // Strength - Chest
  {
    id: "ex-bench-press",
    name: "Barbell Bench Press",
    description: "Lie on a flat bench and press a barbell upward",
    muscleGroup: "Chest",
    workoutTypeId: "wt-strength",
    isSystemExercise: true,
    trackingType: "reps_weight",
  },
  {
    id: "ex-incline-bench",
    name: "Incline Dumbbell Press",
    description: "Press dumbbells on an inclined bench to target upper chest",
    muscleGroup: "Chest",
    workoutTypeId: "wt-strength",
    isSystemExercise: true,
    trackingType: "reps_weight",
  },
  {
    id: "ex-chest-fly",
    name: "Dumbbell Chest Fly",
    description: "Lie flat and open arms wide with dumbbells, then squeeze together",
    muscleGroup: "Chest",
    workoutTypeId: "wt-strength",
    isSystemExercise: true,
    trackingType: "reps_weight",
  },
  {
    id: "ex-pushup",
    name: "Push-Up",
    description: "Classic bodyweight chest exercise",
    muscleGroup: "Chest",
    workoutTypeId: "wt-strength",
    isSystemExercise: true,
    trackingType: "reps_weight",
  },
  // Strength - Back
  {
    id: "ex-deadlift",
    name: "Barbell Deadlift",
    description: "Lift a barbell from the floor to hip height",
    muscleGroup: "Back",
    workoutTypeId: "wt-strength",
    isSystemExercise: true,
    trackingType: "reps_weight",
  },
  {
    id: "ex-barbell-row",
    name: "Barbell Row",
    description: "Bend over and row a barbell to your torso",
    muscleGroup: "Back",
    workoutTypeId: "wt-strength",
    isSystemExercise: true,
    trackingType: "reps_weight",
  },
  {
    id: "ex-pullup",
    name: "Pull-Up",
    description: "Hang from a bar and pull yourself up",
    muscleGroup: "Back",
    workoutTypeId: "wt-strength",
    isSystemExercise: true,
    trackingType: "reps_weight",
  },
  {
    id: "ex-lat-pulldown",
    name: "Lat Pulldown",
    description: "Pull a cable bar down to your chest",
    muscleGroup: "Back",
    workoutTypeId: "wt-strength",
    isSystemExercise: true,
    trackingType: "reps_weight",
  },
  // Strength - Shoulders
  {
    id: "ex-overhead-press",
    name: "Overhead Press",
    description: "Press a barbell or dumbbells overhead",
    muscleGroup: "Shoulders",
    workoutTypeId: "wt-strength",
    isSystemExercise: true,
    trackingType: "reps_weight",
  },
  {
    id: "ex-lateral-raise",
    name: "Lateral Raise",
    description: "Raise dumbbells to the sides to shoulder height",
    muscleGroup: "Shoulders",
    workoutTypeId: "wt-strength",
    isSystemExercise: true,
    trackingType: "reps_weight",
  },
  // Strength - Arms
  {
    id: "ex-bicep-curl",
    name: "Barbell Bicep Curl",
    description: "Curl a barbell upward targeting the biceps",
    muscleGroup: "Biceps",
    workoutTypeId: "wt-strength",
    isSystemExercise: true,
    trackingType: "reps_weight",
  },
  {
    id: "ex-tricep-pushdown",
    name: "Tricep Pushdown",
    description: "Push a cable attachment downward to work triceps",
    muscleGroup: "Triceps",
    workoutTypeId: "wt-strength",
    isSystemExercise: true,
    trackingType: "reps_weight",
  },
  {
    id: "ex-hammer-curl",
    name: "Hammer Curl",
    description: "Curl dumbbells with a neutral grip",
    muscleGroup: "Biceps",
    workoutTypeId: "wt-strength",
    isSystemExercise: true,
    trackingType: "reps_weight",
  },
  // Strength - Legs
  {
    id: "ex-squat",
    name: "Barbell Squat",
    description: "Squat with a barbell on your back",
    muscleGroup: "Legs",
    workoutTypeId: "wt-strength",
    isSystemExercise: true,
    trackingType: "reps_weight",
  },
  {
    id: "ex-leg-press",
    name: "Leg Press",
    description: "Press weight away using a leg press machine",
    muscleGroup: "Legs",
    workoutTypeId: "wt-strength",
    isSystemExercise: true,
    trackingType: "reps_weight",
  },
  {
    id: "ex-lunges",
    name: "Lunges",
    description: "Step forward and lower your body alternating legs",
    muscleGroup: "Legs",
    workoutTypeId: "wt-strength",
    isSystemExercise: true,
    trackingType: "reps_weight",
  },
  {
    id: "ex-leg-curl",
    name: "Leg Curl",
    description: "Curl weight using the hamstring curl machine",
    muscleGroup: "Legs",
    workoutTypeId: "wt-strength",
    isSystemExercise: true,
    trackingType: "reps_weight",
  },
  {
    id: "ex-calf-raise",
    name: "Calf Raise",
    description: "Rise up on your toes to work the calves",
    muscleGroup: "Legs",
    workoutTypeId: "wt-strength",
    isSystemExercise: true,
    trackingType: "reps_weight",
  },
  // Strength - Core
  {
    id: "ex-plank",
    name: "Plank",
    description: "Hold a straight body position on forearms and toes",
    muscleGroup: "Core",
    workoutTypeId: "wt-strength",
    isSystemExercise: true,
    trackingType: "duration",
  },
  {
    id: "ex-crunch",
    name: "Crunch",
    description: "Lie on your back and curl your torso upward",
    muscleGroup: "Core",
    workoutTypeId: "wt-strength",
    isSystemExercise: true,
    trackingType: "reps_weight",
  },
  // Strength - Glutes
  {
    id: "ex-hip-thrust",
    name: "Hip Thrust",
    description: "Thrust hips upward with back against a bench",
    muscleGroup: "Glutes",
    workoutTypeId: "wt-strength",
    isSystemExercise: true,
    trackingType: "reps_weight",
  },
  // Cardio
  {
    id: "ex-running",
    name: "Running",
    description: "Run outdoors or on a treadmill",
    muscleGroup: "Cardio",
    workoutTypeId: "wt-cardio",
    isSystemExercise: true,
    trackingType: "distance",
  },
  {
    id: "ex-cycling",
    name: "Cycling",
    description: "Ride a bike or use a stationary cycle",
    muscleGroup: "Cardio",
    workoutTypeId: "wt-cardio",
    isSystemExercise: true,
    trackingType: "distance",
  },
  {
    id: "ex-rowing",
    name: "Rowing Machine",
    description: "Use a rowing machine for full body cardio",
    muscleGroup: "Cardio",
    workoutTypeId: "wt-cardio",
    isSystemExercise: true,
    trackingType: "distance",
  },
  {
    id: "ex-jump-rope",
    name: "Jump Rope",
    description: "Skip rope for cardio conditioning",
    muscleGroup: "Cardio",
    workoutTypeId: "wt-cardio",
    isSystemExercise: true,
    trackingType: "duration",
  },
  {
    id: "ex-swimming",
    name: "Swimming",
    description: "Swim laps for full body cardio workout",
    muscleGroup: "Cardio",
    workoutTypeId: "wt-cardio",
    isSystemExercise: true,
    trackingType: "distance",
  },
  // HIIT
  {
    id: "ex-burpees",
    name: "Burpees",
    description: "Full body explosive movement combining squat, push-up, and jump",
    muscleGroup: "Full Body",
    workoutTypeId: "wt-hiit",
    isSystemExercise: true,
    trackingType: "reps_weight",
  },
  {
    id: "ex-mountain-climbers",
    name: "Mountain Climbers",
    description: "Alternate driving knees toward chest in plank position",
    muscleGroup: "Full Body",
    workoutTypeId: "wt-hiit",
    isSystemExercise: true,
    trackingType: "duration",
  },
  {
    id: "ex-box-jumps",
    name: "Box Jumps",
    description: "Jump onto a raised platform from a standing position",
    muscleGroup: "Legs",
    workoutTypeId: "wt-hiit",
    isSystemExercise: true,
    trackingType: "reps_weight",
  },
  {
    id: "ex-kettlebell-swing",
    name: "Kettlebell Swing",
    description: "Swing a kettlebell from between your legs to chest height",
    muscleGroup: "Full Body",
    workoutTypeId: "wt-hiit",
    isSystemExercise: true,
    trackingType: "reps_weight",
  },
  // Flexibility
  {
    id: "ex-yoga-flow",
    name: "Yoga Flow",
    description: "A series of yoga poses performed in sequence",
    muscleGroup: "Full Body",
    workoutTypeId: "wt-flexibility",
    isSystemExercise: true,
    trackingType: "duration",
  },
  {
    id: "ex-hamstring-stretch",
    name: "Hamstring Stretch",
    description: "Stretch the back of the thigh",
    muscleGroup: "Legs",
    workoutTypeId: "wt-flexibility",
    isSystemExercise: true,
    trackingType: "duration",
  },
  {
    id: "ex-foam-rolling",
    name: "Foam Rolling",
    description: "Use a foam roller for myofascial release",
    muscleGroup: "Full Body",
    workoutTypeId: "wt-flexibility",
    isSystemExercise: true,
    trackingType: "duration",
  },
];
